all:
#	cd broadcom; make
	cd intel; make
	cd chelsio/cxgb4; make
#	cd neterion; make
#	cd myricom; make

clean:
#	cd broadcom; make clean
	cd intel; make clean
	cd chelsio/cxgb4; make clean
#	cd neterion; make clean
#	cd myricom; make clean

